language: csharp
mono: none
dotnet: 2.2.103
install:
  - dotnet restore
  - nuget restore solution-name.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - dotnet build
  - dotnet test Minoraut.Todo.Tests/Minotaur.Todo.Tests.csproj