version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - minotaur-app
    # network_mode: host
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    containter_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - minotaur-app
    # network_mode: host
    volumes:
      - rabbitmq:/var/lib/rabbimtq

  redis:
    image: redis
    containter_name: redis
    ports:
      - 6379:6379
    networks:
      - minotaur-app
    # network_mode: host
    volumes:
      - redis:/data

networks:
  minotaur-app:
    name: minotaur-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local